name: Unit Tests

on:
  # if pushed directly to the master
  push:
    branches:
      - master
      - release/*
  # on a pull request
  pull_request:
    branches:
      - master
      - release/*

jobs:

  build:
    name: Build all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install Libs
        run: yarn install

      - name: Build
        run: yarn workspaces run build

  tests:
    name: Test All
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install Libs
        run: yarn install

      - name: Test (node)
        run: yarn workspace @emeraldpay/api-node run test
      - name: Test (web)
        run: yarn workspace @emeraldpay/api-web run test
